version: "3.9"
services:
  master:
    image: master
    build:
      context: .
      dockerfile: ./master.Dockerfile
    command: ['cargo', 'run', '--release', '--bin', 'master']
    ports:
      - "8080:8080"
    depends_on:
      - secondary
      - secondary2

  secondary:
    image: secondary
    build:
      context: .
      dockerfile: ./secondary.Dockerfile
    command: ['cargo', 'run', '--release', '--bin', 'secondary', '8081']
    ports:
      - "8081:8081"

  secondary2:
    image: secondary2
    build:
      context: .
      dockerfile: ./secondary.Dockerfile
    command: ['cargo', 'run', '--release', '--bin', 'secondary', '8082']
    ports:
      - "8082:8082"