version: "3.9"
services:
  master:
    image: master
    build:
      context: .
      dockerfile: ./master.Dockerfile
    command: ['cargo', 'run', '--release', '--bin', 'master']
    ports:
      - "8000:8000"
    depends_on:
      - secondary
      - secondary2

  secondary:
    image: secondary
    build:
      context: .
      dockerfile: ./secondary.Dockerfile
    command: ['cargo', 'run', '--release', '--bin', 'secondary', '8001']
    ports:
      - "8001:8001"

  secondary2:
    image: secondary2
    build:
      context: .
      dockerfile: ./secondary.Dockerfile
    command: ['cargo', 'run', '--release', '--bin', 'secondary', '8002']
    ports:
      - "8002:8002"